# Generated by Django 5.1.7 on 2025-03-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'muscles',
            },
        ),
        migrations.CreateModel(
            name='StrengthExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'strength_exercises',
            },
        ),
        migrations.CreateModel(
            name='StrengthExerciseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.strengthexercise')),
            ],
            options={
                'db_table': 'strength_exercise_events',
            },
        ),
        migrations.CreateModel(
            name='StrengthExerciseNxNMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.strengthexercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.muscle')),
            ],
            options={
                'db_table': 'strength_exercises_nxn_muscles',
            },
        ),
        migrations.AddField(
            model_name='strengthexercise',
            name='muscles_worked',
            field=models.ManyToManyField(through='fitness.StrengthExerciseNxNMuscle', to='fitness.muscle'),
        ),
    ]
