# Generated by Django 5.1.3 on 2024-12-02 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthExerciseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('set_count', models.PositiveSmallIntegerField()),
                ('reps_per_set', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('strength_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.strengthexercise')),
            ],
        ),
    ]
