# Generated by Django 5.1.3 on 2024-12-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_flexibilityexercise_flexibilityexerciseevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexibilityexercise',
            name='name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='strengthexercise',
            name='name',
            field=models.CharField(max_length=48),
        ),
    ]
