# Generated by Django 5.1.7 on 2025-04-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_strengthexerciseevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strengthexercise',
            name='muscles_worked',
        ),
        migrations.RemoveField(
            model_name='strengthexercisenxnmuscle',
            name='muscle',
        ),
        migrations.RemoveField(
            model_name='strengthexercisenxnmuscle',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='Muscle',
        ),
        migrations.DeleteModel(
            name='StrengthExerciseNxNMuscle',
        ),
    ]
