# Generated by Django 5.1.7 on 2025-04-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_remove_strengthexercise_muscles_worked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strengthexerciseevent',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
