# Generated by Django 5.1.7 on 2025-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_alter_strengthexerciseevent_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strengthexerciseevent',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
