# Generated by Django 5.2 on 2025-05-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_brainmaterial_brainevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardioexerciseevent',
            name='distance',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
