# Generated by Django 5.2.1 on 2025-05-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_cardioexerciseevent_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioexerciseevent',
            name='distance',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
