# Generated by Django 5.2.1 on 2025-06-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_rename_brainmaterial_brainexercise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brainevent',
            old_name='material',
            new_name='exercise',
        ),
    ]
