# Generated by Django 5.2.1 on 2025-06-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_rename_material_brainevent_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioevent',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='strengthevent',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
