# Generated by Django 5.1.7 on 2025-03-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'muscles',
            },
        ),
        migrations.CreateModel(
            name='StrengthExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'strength_exercises',
            },
        ),
        migrations.CreateModel(
            name='StrengthExerciseEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_tracker.strengthexercises')),
            ],
            options={
                'db_table': 'strength_exercise_events',
            },
        ),
        migrations.CreateModel(
            name='StrengthExercisesNxNMuscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_tracker.strengthexercises')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_tracker.muscles')),
            ],
            options={
                'db_table': 'strength_exercises_nxn_muscles',
            },
        ),
        migrations.AddField(
            model_name='strengthexercises',
            name='muscles_worked',
            field=models.ManyToManyField(through='fitness_tracker.StrengthExercisesNxNMuscles', to='fitness_tracker.muscles'),
        ),
    ]
